name: GitHub Actions Linter Formatter Demo
on: [pull_request]

jobs:
  format-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Get node version
        id: node
        run: echo "NODE_VERSION=$(node -v)" >> $GITHUB_ENV

      - name: Get node_modules cache
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ env.NODE_VERSION }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Check File Structure
        run: |
          echo "Current Directory:"
          pwd
          echo "Files in Current Directory:"
          ls -la
          echo "Node Modules:"
          if [ -d "node_modules" ]; then
            echo "node_modules exists."
            ls -la node_modules
          else
            echo "node_modules does not exist."
          fi

      - name: Install Dependencies
        run: npm install eslint prettier

      - name: Run Formatter
        run: npx prettier --check .

      - name: Run ESLint
        run: npx eslint . --max-warnings=0
