name: Format and Lint Code

on: [push]

jobs:
  lint-format:
  runs-on: ubuntu-latest
  steps:
    - name: Install Node
    - uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install ESLint and Prettier
      run: npm install -D eslint prettier

    - name: Run Linter
      run: npx eslint .

    - name: Run Formatter
      run: npx prettier --write .
